### PR TITLE
Add user page

### PR DESCRIPTION
**Pull request by LofiSu**
image

### CODE REVIEW

**Comment by LofiSu** [comment]
image

**Comment by chaokunyang** [comment]
how about adding `yarn.lock` to git ignored files

**Review by LofiSu — COMMENTED** [review]
maybe next time 
I delete yarn.lock

**Comment by chaokunyang** [comment]
Could wr delete first sense in the usage page. Wr may add it if we have more users

**Review by chaokunyang — APPROVED** [review]

**Pull request merged**
