### PR TITLE
infra: add github action ci

### PR DESCRIPTION
**Pull request by yuluo-yx**

### CODE REVIEW

**Review by chaokunyang — APPROVED** [review]
Looks great, thanks

**Comment by yuluo-yx** [comment]
> Looks great, thanks

Thanks, it looks like there was some problem with the formatting of the previous document that caused the ci detection to fail. Please give me some time, I will fix the formatting in the document and make sure the document passes the lint detection.

**Comment by yuluo-yx** [comment]
hi @chaokunyang I find dead link,

```
FILE: ./docs/community/how_to_verify.md
[✖] [https://repository.apache.org/content/repositories/orgapachefury-${maven_artifact_number}/](https://repository.apache.org/content/repositories/orgapachefury-$%7Bmaven_artifact_number%7D/)

2 links checked.

ERROR: 1 dead links found!
[✖] https://repository.apache.org/content/repositories/orgapachefury-${maven_artifact_number}/ → Status: [40](https://github.com/yuluo-yx/fury-site/actions/runs/10399102664/job/28797493138?pr=1#step:5:41)4
```
Is there an alternative solution?

more info: https://github.com/yuluo-yx/fury-site/actions/runs/10399102664/job/28797493138?pr=1

**Comment by chaokunyang** [comment]
> hi @chaokunyang I find dead link,
> 
> ```
> FILE: ./docs/community/how_to_verify.md
> [✖] [https://repository.apache.org/content/repositories/orgapachefury-${maven_artifact_number}/](https://repository.apache.org/content/repositories/orgapachefury-$%7Bmaven_artifact_number%7D/)
> 
> 2 links checked.
> 
> ERROR: 1 dead links found!
> [✖] https://repository.apache.org/content/repositories/orgapachefury-${maven_artifact_number}/ → Status: [40](https://github.com/yuluo-yx/fury-site/actions/runs/10399102664/job/28797493138?pr=1#step:5:41)4
> ```
> 
> Is there an alternative solution?
> 
> more info: https://github.com/yuluo-yx/fury-site/actions/runs/10399102664/job/28797493138?pr=1

Could we add hint to skip specified links and lines?

**Comment by yuluo-yx** [comment]
I have run all ci in local repository, ptal @chaokunyang 
image

**Pull request merged**
