### PR TITLE
[New Feature]Add AOS animations to Fury website for enhanced scroll effects

### PR DESCRIPTION
**Pull request by LofiSu**
Add AOS animations to Fury website

- Integrated AOS (Animate On Scroll) library
- Applied animations to various sections of the site
- Improved user experience with smooth scroll effects

### CODE REVIEW

**Comment by PragmaTwice** [comment]
Could you attach a screenshot or recording to show the changes you made?

**Comment by LofiSu** [comment]
> Could you attach a screenshot or recording to show the changes you made?

This is the animation effect, you can open the screen and run it. I have sent it to the author, and he said yes.

**Comment by chaokunyang** [comment]
> > Could you attach a screenshot or recording to show the changes you made?
> 
> This is the animation effect, you can open the screen and run it. I have sent it to the author, and he said yes.

We can capture three pictures of the animation to show a simple diff here

**Comment by LofiSu** [comment]
https://github.com/user-attachments/assets/5c41140e-879b-4520-bd88-7747879285ab

**Comment by chaokunyang** [comment]
You did not delete yarn.lock file, and the animations has been added in #147

**Comment by LofiSu** [comment]
> You did not delete yarn.lock file, and the animations has been added in #147

I'm sorry I didn't double check, I've deleted it.

**Pull request closed without merging**
